export class ConstStr{
  static readonly WORKSHOP = 'workshop'
  static readonly SHOP = 'shop'
  static readonly ACCIDENT = 'accident'
  static readonly SKILLTREE = 'skillTree'

  static readonly WORKSHOP_STORAGE_URL = 'workshopUrl'
  static readonly SHOP_STORAGE_URL = 'shopUrl';
  static readonly ACCIDENT_STORAGE_URL = 'accidentUrl';
  static readonly SKILLTREE_STORAGE_URL = 'skillTreeUrl';

  static readonly TOTAL_COOKIES = 'totalCookies'
}