export class ConstStr{
  static readonly WORKSHOP = 'workshop'
  static readonly SHOP = 'shop'
  static readonly ACCIDENT = 'accident'
  static readonly SKILLTREE = 'skillTree'

  static readonly WORKSHOP_STORAGE_URL = 'workshopUrl'
  static readonly SHOP_STORAGE_URL = 'shopUrl';
  static readonly ACCIDENT_STORAGE_URL = 'accidentUrl';
  static readonly SKILLTREE_STORAGE_URL = 'skillTreeUrl';

  // 基础数据存储str
  static readonly TOTAL_COOKIES = 'totalCookies'
  static readonly TOTAL_PSC = 'totalPSC'

  static readonly PLAYER_LIST = 'playerList'
  // 设备类型常量
  static readonly DEVICE_CURSOR = '光标'
  static readonly DEVICE_GRANDMA = '奶奶'
  static readonly DEVICE_FARM = '农场'
  static readonly DEVICE_MINE = '矿山'
  static readonly DEVICE_FACTORY = '工厂'
  static readonly DEVICE_BANK = '银行'
  static readonly DEVICE_TEMPLE = '神庙'
  static readonly DEVICE_WIZARD_TOWER = '巫师塔'
  static readonly DEVICE_SPACESHIP = '飞船'
  static readonly DEVICE_ALCHEMY_LAB = '炼金实验室'
  static readonly DEVICE_PORTAL = '传送门'
  static readonly DEVICE_TIME_MACHINE = '时间机器'
  static readonly DEVICE_ANTIMATTER_CONDENSER = '反物质冷凝器'
  static readonly DEVICE_PRISM = '棱镜'
  static readonly DEVICE_CHANCEMAKER = '机会制造者'
}